name: CityOfLight
favicon: null
layout_spectrum: 0.7147031531203538
typography_spectrum: 0.5620929922442883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2335341868456453
  lightness: 0.2769737371709198
  saturation: 0.9968609819188714
  rhythmicContrast: 0.6394990724511445
purpose: []
